# Generated by Django 5.0.7 on 2024-08-11 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_multiple_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiple',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
