# Generated by Django 5.0.7 on 2024-08-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_multiple_date_multiple_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='timestamps',
        ),
    ]
