# Generated by Django 5.0.7 on 2024-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_remove_usercredentials_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='emailId',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
