# Generated by Django 5.0.7 on 2024-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_usercredentials_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='emailId',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
