# Generated by Django 5.0.7 on 2024-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_usercredentials_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='emailId',
        ),
    ]
