# Generated by Django 5.1.2 on 2024-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
